play_song:
	clr Legato
	mov r3, #fast
	playNote(A3, sixteenth)
	playNote(A4, sixteenth)
	playNote(C5, sixteenth)
	poly(D4,D5,eighth)
	playNote(D5,eighth)
	playNote(D4, eighth)
	playNote(D5,sixteenth)
	playNote(E5,sixteenth)
	poly(F5, AS3, eighth)
	playNote(F5, eighth)
	playNote(AS3, eighth)
	playNote(F5, sixteenth)
	playNote(G5, sixteenth)
	poly(E5, A3, eighth)
	playNote(E5, eighth)
	playNote(A3, eighth)
	playNote(D5, sixteenth)
	playNote(C5, sixteenth)
	poly(C5, D4, sixteenth)
	playNote(D5, quarter)
	playNote(D4, sixteenth)
	playNote(A4, sixteenth)
	playNote(C5, eighth)
	poly(AS3,D5,eighth)
	playNote(D5,eighth)
	playNote(AS3, eighth)
	playNote(D5,sixteenth)
	playNote(E5,sixteenth)
	poly(F5, F3, eighth)
	playNote(F5, eighth)
	playNote(F3, eighth)
	playNote(F5, sixteenth)
	playNote(G5, sixteenth)
	poly(E5, C4, eighth)
	playNote(E5, eighth)
	playNote(C4, eighth)
	playNote(D5, sixteenth)
	playNote(C5, sixteenth)
	poly(D5, D4, dot_eighth)
	playNote(D3, sixteenth)
	playNote(D3, sixteenth)
	playNote(A4, sixteenth)
	playNote(C5, sixteenth)
	poly(D4,D5,eighth)
	playNote(D5,eighth)
	playNote(D4, eighth)
	playNote(D5,sixteenth)
	playNote(E5,sixteenth)
	poly(G5, AS3, eighth)
	playNote(G5, eighth)
	playNote(AS3, eighth)
	playNote(G5,sixteenth)
	playNote(A5,sixteenth)
	poly(AS5, G3, eighth)
	playNote(AS5, eighth)
	playNote(G3, eighth)
	playNote(A5,sixteenth)
	playNote(G5,sixteenth)
	poly(A5,D4,sixteenth)
	playNote(D5, eighth)
	playNote(D4, eighth)
	playNote(D5,sixteenth)
	playNote(E5,sixteenth)
	poly(F5, AS3, eighth)
	playNote(F5, eighth)
	playNote(AS3, eighth)
	playNote(G5, eighth)
	playNote(A5,sixteenth)
	playNote(D5,eighth)
	playNote(A3, eighth)
	playNote(D5,sixteenth)
	playNote(F5,sixteenth)
	Poly(E5, A3, eighth)
	playNote(E5, eighth)
	playNote(A3, eighth)
	playNote(F5, sixteenth)
	playNote(D5, sixteenth)	
	Poly(E5, A3, eighth)
	playNote(rest,quarter)
ret
	
