play_song:
	setb Legato
	mov R3, #Slow
	playNote(D6, grace)
	playNote(E6, eighth)
	playNote(D6, sixteenth)
	playNote(A5, dot_eighth)
	playNote(F5, eighth)
;	playNote(rest, sixteenth)
	playNote(D6, grace)
	playNote(E6, eighth)
	playNote(D6, sixteenth)
	playNote(A5, dot_eighth)
	playNote(F5, eighth)
;	playNote(rest, sixteenth)
	
	playNote(AS5, grace)
	playNote(C6, eighth)
	playNote(AS5, sixteenth)
	playNote(F5, dot_eighth)
	playNote(D5, eighth)
;	playNote(rest, sixteenth)
	playNote(AS5, grace)
	playNote(C6, eighth)
	playNote(AS5, sixteenth)
	playNote(F5, dot_eighth)
	playNote(D5, eighth)
;	playNote(rest, sixteenth)
	
	playNote(A5, grace)
	playNote(AS5, eighth)
	playNote(A5, sixteenth)
	playNote(F5, dot_eighth)
	playNote(D5, eighth)
	playNote(AS4, dot_quarter)
	playNote(rest, eighth)
	playNote(A4, grace)
	playNote(AS4, grace)
	playNote(A4, eighth)
	playNote(AS4, eighth)
	playNote(C5,eighth)
	playNote(D5, eighth)
	playNote(E5, eighth)
	playNote(F5, eighth)
	playNote(G5, eighth)
	playNote(A5, eighth)	
	ret